
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Run unit tests for the application
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "vale78"
    
  ui-tests:
    runs-on: ubuntu-latest
    needs: build-unit-test

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Use Node.js18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install project dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start the application
      run: npx start &
    - name: Run UI tests for the application
      run: npm run test:ui

